force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como um objeto de junção para juntar Contato e habilidade</description>
    <label>Habilidade do contato</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>Habilidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do contato</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel da habilidade do contato</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Ranking dos habilidades do contato</description>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HabilidadeContatoBO.cls
public class HabilidadeContatoBO {
	private static final HabilidadeContatoBO instance = new HabilidadeContatoBO();
    
    private HabilidadeContatoBO(){
        
    }
    
    public static HabilidadeContatoBO getInstance(){
        return instance;
    }
    
    public void atualizaRanking(Set<Id> idsContato){
        Map<Id,Contact> mapContatosRevisarRanking = new Map<Id,Contact>([SELECT Id, 
                                                                             		(SELECT Id, Name, Level__c FROM Habilidades__r 
                                                                                     WHERE Level__c != null ORDER BY Level__c DESC, name) 
                                                                             FROM Contact 
                                                                             WHERE Id in : idsContato]);
        
        List<HabilidadeContato__c> habilidadesParaAtualizarRanking = new List<HabilidadeContato__c>();
            for(Contact contato : mapContatosRevisarRanking.values())
            {
                if(!contato.Habilidades__r.isEmpty())
                {
                    Integer ranking = 1;
                    for(HabilidadeContato__c habilidadeContato : contato.Habilidades__r)
                    {
                        habilidadeContato.Ranking__c = ranking++;
                        habilidadesParaAtualizarRanking.add(habilidadeContato);
                    }
                }
            }
            
            TriggerHandler.bypass('HabilidadeContatoTriggerHandler');
            update habilidadesParaAtualizarRanking;
            TriggerHandler.clearBypass('HabilidadeContatoTriggerHandler');
    }
}