force-app/main/default/objects/Contact/fields/NivelHeroi__c.field-meta.xml
<CustomField>
    <fullName>NivelHeroi__c</fullName>
    <label>Nivel do herói</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aspira</fullName>
            </value>
            <value>
                <fullName>Junior</fullName>
            </value>
            <value>
                <fullName>Pleno</fullName>
            </value>
            <value>
                <fullName>Senior</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Heroi.recordType-meta.xml
<RecordType>
    <fullName>Heroi</fullName>
    <active>true</active>
    <description>Contato do tipo herói</description>
    <label>Herói</label>
</RecordType>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como um objeto de junção para juntar Contato e habilidade</description>
    <label>Habilidade do contato</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>Habilidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel da habilidade do contato</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/IdentificarNivelHeroiFlow.cls
global class IdentificarNivelHeroiFlow {

    @InvocableMethod(label = 'Identifica Nivel do Heroi')
    public static List<Contact> identificaNivelHeroi(List<contactRequest> requests){
        
        List<Contact> contatos = new List<Contact>();
        
        for(contactRequest request : requests){
            Decimal media = 0;
            Decimal somaLevel = 0; 
            
            for(HabilidadeContato__c habilidadeContato : request.habilidadesContato){
                somaLevel += habilidadeContato.Level__c;
            }
            
            media = somaLevel/request.habilidadesContato.size();
            
            String nivel = '';
            if(media >= 80){
            	nivel = 'Senior'; 	   
            }else if(media >= 40 && media < 80 ){
                nivel = 'Pleno';
            }else{
                nivel = 'Junior';
            }
            
            System.debug('Nivel: '+nivel);
            system.debug('Habilidades contato size: '+request.habilidadesContato.size());
            System.debug('media: '+media);
            System.debug('somaLevel: '+somaLevel);
            
            request.contact.NivelHeroi__c = nivel;
            contatos.add(request.contact);
        }
        
        update contatos;
		return contatos;        
    }
    
    global class contactRequest{
        @InvocableVariable(required=true)
        global Contact contact;
        @InvocableVariable(required=true)
        global List<HabilidadeContato__c> habilidadesContato;
    }
    
}