force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Informar o nome de guerra do vilão ou herói</description>
    <inlineHelpText>Informar o nome de guerra do vilão ou herói</inlineHelpText>
    <label>Nome de guerra</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status_candidato__c.field-meta.xml
<CustomField>
    <fullName>Status_candidato__c</fullName>
    <label>Status candidato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em análise</fullName>
            </value>
            <value>
                <fullName>Reprovado na análise</fullName>
            </value>
            <value>
                <fullName>Aguardadndo aprovação p/ treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado na análise do gestor</fullName>
            </value>
            <value>
                <fullName>Em treinamento</fullName>
            </value>
            <value>
                <fullName>Reprovado no treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado pelo treinamento</fullName>
            </value>
            <value>
                <fullName>Aprovado direto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Habilidade dos heróis</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como um objeto de junção para juntar Contato e habilidade</description>
    <label>Habilidade do contato</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>Habilidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do contato</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do contato</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel da habilidade do contato</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Ranking__c.field-meta.xml
<CustomField>
    <fullName>Ranking__c</fullName>
    <description>Ranking dos habilidades do contato</description>
    <label>Ranking</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HabilidadeContatoTest.cls
@IsTest
public class HabilidadeContatoTest {
	@testSetup
    public static void setup(){
        Contact cap = new Contact(firstName = 'Steven', lastName= 'rogers', NomeGuerra__c='Capitão america',Status_candidato__c = 'Aprovado direto');
        Contact viuva = new Contact(firstName = 'Natasha', lastName= 'romanova', NomeGuerra__c='viuva negra',Status_candidato__c = 'aprovado direto');
        List<Contact> herois = new List<Contact> {cap, viuva};
        insert herois;
        
        Habilidade__c supForca = new Habilidade__c(name = 'Super forte');
        Habilidade__c art = new Habilidade__c(name = 'Artes marciais');
        
        List<Habilidade__c> habilidades = new List<Habilidade__c>();
        habilidades.add(supForca);
        habilidades.add(art);
        insert habilidades;
        
        HabilidadeContato__c  habilidadeContato_1 = new HabilidadeContato__c();
        habilidadeContato_1.Contato__c = cap.Id;
        habilidadeContato_1.Habilidade__c = supForca.Id;
        habilidadeContato_1.Level__c = 90;
        
        HabilidadeContato__c  habilidadeContato_2 = new HabilidadeContato__c();
        habilidadeContato_2.Contato__c = viuva.Id;
        habilidadeContato_2.Habilidade__c = art.Id;
        habilidadeContato_2.Level__c = 40;
        
        List<HabilidadeContato__c> habiliContatos = 
        new List<HabilidadeContato__c> {habilidadeContato_1, habilidadeContato_2};
        
        insert habiliContatos;
    }
    
    @IsTest
    public static void validaNovoRankingBaforeUpdate(){
        List<HabilidadeContato__c> habilidadesValida = [select id, Habilidade__r.name , ranking__c
                                                  from HabilidadeContato__c 
                                                  where contato__r.NomeGuerra__c = 'Capitão america'
                                                 and ranking__c != null];
        
        //System.assert(habilidadesValida.size() == 1);
        System.assertEquals(1, habilidadesValida.size());
        
        for(HabilidadeContato__c habContato : habilidadesValida){
            
            switch on habContato.Habilidade__r.name{
                when 'Super forte'{
                    System.assertEquals(1, habContato.Ranking__c);
                }
            }
        }
    }
    
    @isTest
    public static void validaQuandoRankingNulo(){
        HabilidadeContato__c habilidadeContato = [select id, ranking__c from habilidadeContato__c 
                                                  where Contato__r.NomeGuerra__c = 'viuva negra'
                                                 and habilidade__r.name = 'Artes marciais'];
        
        System.assertEquals(null, habilidadeContato.Ranking__c);
    }
    
    @isTest
    public static void validaQuandoRankingAfterUpdate(){
        List<HabilidadeContato__c> habilidadesContato = [select id, Habilidade__r.name , ranking__c
                                                  		from HabilidadeContato__c 
                                                        order by Contato__r.nomeGuerra__c];
    }
}