force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Informar o nome de guerra do vilão ou herói</description>
    <inlineHelpText>Informar o nome de guerra do vilão ou herói</inlineHelpText>
    <label>Nome de guerra</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Habilidade__c/Habilidade__c.object-meta.xml
<CustomObject>
    <description>Habilidade dos heróis</description>
    <label>Habilidade</label>
    <nameField>
        <label>Habilidade</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Habilidades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como um objeto de junção para juntar Contato e habilidade</description>
    <label>Habilidade do contato</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>Habilidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do contato</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Habilidade__c.field-meta.xml
<CustomField>
    <fullName>Habilidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Habilidade</label>
    <referenceTo>Habilidade__c</referenceTo>
    <relationshipLabel>Habilidades do contato</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>Nivel da habilidade do contato</description>
    <label>Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EditarContatoHabilidadesExtension.cls
public with sharing class EditarContatoHabilidadesExtension {

    private Contact contato;
    public List<Habilidadecontato__c> habilidades {get; private set;}

    public EditarContatoHabilidadesExtension(ApexPages.StandardController controller) {
        this.contato = (Contact) controller.getRecord();
        this.habilidades = [select id, habilidade__r.name, level__c from Habilidadecontato__c where contato__c = :this.contato.Id];
    }

    public PageReference cancelar(){
        PageReference pg = new PageReference('/'+this.contato.Id);
        pg.setRedirect(true);
        return pg;
    }

    public void salvar(){
        try {
            update this.contato;
            update this.habilidades;

            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM, 'Salvo !!!'));
        }
        catch(Exception e){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, e.getMessage()));
            system.debug('Error: '+e.getMessage());
        }
    }

    public PageReference seeHeroDetails(){
        //https://www.marvel.com/characters/{{first hero name}}-{{last hero name}}-{{name}}-{{lastname}}
        List<String> heroName = contato.NomeGuerra__c.split(' ');
        PageReference pg = new PageReference('https://www.marvel.com/characters/'+heroName.get(0)+'-'+heroName.get(1)+'-'+contato.firstName.toLowerCase()+'-'+contato.lastName.toLowerCase());
        pg.setRedirect(true);
        return pg;

        //System.debug('Nome de guerra: '+contato.NomeGuerra__c);
    }
}