force-app/main/default/objects/Contact/fields/NomeGuerra__c.field-meta.xml
<CustomField>
    <fullName>NomeGuerra__c</fullName>
    <description>Informar o nome de guerra do vilão ou herói</description>
    <inlineHelpText>Informar o nome de guerra do vilão ou herói</inlineHelpText>
    <label>Nome de guerra</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HabilidadeContato__c/HabilidadeContato__c.object-meta.xml
<CustomObject>
    <description>Usado como um objeto de junção para juntar Contato e habilidade</description>
    <label>Habilidade do contato</label>
    <nameField>
        <displayFormat>HC-{00000}</displayFormat>
        <label>Habilidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Habilidades do contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/HabilidadeContato__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Habilidades do contato</relationshipLabel>
    <relationshipName>Habilidades</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SOQL.cls
public class SOQL {
	
    public static List<Contact> getAllContacts(){
        List<Contact> contatos = [select id, name from Contact];
        return contatos;
    }
    
    public static Contact getContactById(String id){
        return [select id, name from Contact where id = :id];
    }
    
    public static Map<String, Decimal> getAverage(){
        AggregateResult[] results = [select Contato__r.NomeGuerra__c nomeGuerra, count(id) idcont from HabilidadeContato__c group by Contato__r.NomeGuerra__c];
        
        Map<String, Decimal> mapa = new Map<String, Decimal>();
        
        for(AggregateResult result : results){
            String nomeGuerra = (String) result.get('nomeGuerra');
            Decimal media = (Decimal) result.get('idcont');
            
            mapa.put(nomeGuerra, media);
        }
        return mapa;
    }
}